// Package blob stores uploaded files and terminal transcripts (spec §13: "Files … → S3-compatible object storage"):
// S3 in production, a directory locally.
package blob

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"

	"crucible/internal/apperr"
)

type Store interface {
	Put(ctx context.Context, key string, body io.ReadSeeker, size int64) error
	Get(ctx context.Context, key string) (io.ReadCloser, error)
}

// Keys are generated by the server; anything else is a bug or an attack.
var validKey = regexp.MustCompile(`^uploads/[a-z0-9_-]+(/[a-z0-9_-]+)*$`)

// MaxSize bounds a single blob (uploads and transcripts are small; this stops a runaway body filling the disk or bucket).
const MaxSize = 32 << 20

func check(key string) error {
	if len(key) > 256 || !validKey.MatchString(key) {
		return fmt.Errorf("blob: invalid key %q", key)
	}
	return nil
}

func checkSize(size int64) error {
	if size < 0 || size > MaxSize {
		return fmt.Errorf("blob: size %d outside 0..%d", size, int64(MaxSize))
	}
	return nil
}

var notFound = apperr.Wrap(apperr.NotFound, "file not found")

// Disk keeps blobs under Dir. ponytail: one directory on one node; use S3 when the API runs anywhere it can lose its disk.
type Disk struct{ Dir string }

// path validates key and returns its file path, refusing any symlink on the way below Dir.
func (d Disk) path(key string) (string, error) {
	if err := check(key); err != nil {
		return "", err
	}
	root := filepath.Clean(d.Dir)
	p := filepath.Join(root, filepath.FromSlash(key))
	if rel, err := filepath.Rel(root, p); err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("blob: key %q escapes the store", key)
	}
	cur := root
	for _, part := range strings.Split(key, "/") {
		cur = filepath.Join(cur, part)
		fi, err := os.Lstat(cur)
		if errors.Is(err, os.ErrNotExist) {
			break
		}
		if err != nil {
			return "", err
		}
		if fi.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("blob: key %q crosses a symlink", key)
		}
	}
	return p, nil
}

func (d Disk) Put(_ context.Context, key string, body io.ReadSeeker, size int64) error {
	if err := checkSize(size); err != nil {
		return err
	}
	p, err := d.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		return err
	}
	if p, err = d.path(key); err != nil { // re-check after MkdirAll created any parents
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(p), ".put-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name()) // no-op after the rename
	n, err := io.Copy(f, io.LimitReader(body, size+1))
	if err != nil {
		f.Close()
		return err
	}
	if n != size {
		f.Close()
		return fmt.Errorf("blob: body is %d bytes, declared %d", n, size)
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), p)
}

func (d Disk) Get(_ context.Context, key string) (io.ReadCloser, error) {
	p, err := d.path(key)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(p)
	if errors.Is(err, os.ErrNotExist) {
		return nil, notFound
	}
	if err != nil {
		return nil, err
	}
	if fi, err := f.Stat(); err != nil || !fi.Mode().IsRegular() {
		f.Close()
		return nil, notFound
	}
	return f, nil
}

type S3 struct {
	Client *s3.Client
	Bucket string
}

// NewS3 uses the default AWS credential chain (the node's instance role in production). endpoint is for tests and
// S3-compatible stores; it switches to path-style addressing.
func NewS3(ctx context.Context, bucket, region, endpoint string) (*S3, error) {
	cfg, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion(region))
	if err != nil {
		return nil, err
	}
	return &S3{Bucket: bucket, Client: s3.NewFromConfig(cfg, func(o *s3.Options) {
		if endpoint != "" {
			o.BaseEndpoint, o.UsePathStyle = aws.String(endpoint), true
		}
		// No flexible checksums: bodies are seekable and SigV4 signs the payload hash; trailers break plain-HTTP fakes.
		o.RequestChecksumCalculation = aws.RequestChecksumCalculationWhenRequired
		o.ResponseChecksumValidation = aws.ResponseChecksumValidationWhenRequired
	})}, nil
}

func (s *S3) Put(ctx context.Context, key string, body io.ReadSeeker, size int64) error {
	if err := check(key); err != nil {
		return err
	}
	if err := checkSize(size); err != nil {
		return err
	}
	_, err := s.Client.PutObject(ctx, &s3.PutObjectInput{Bucket: aws.String(s.Bucket), Key: aws.String(key), Body: body,
		ContentLength: aws.Int64(size), ContentType: aws.String("application/octet-stream"),
		ServerSideEncryption: types.ServerSideEncryptionAes256})
	return err
}

func (s *S3) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	if err := check(key); err != nil {
		return nil, err
	}
	out, err := s.Client.GetObject(ctx, &s3.GetObjectInput{Bucket: aws.String(s.Bucket), Key: aws.String(key)})
	var nsk *types.NoSuchKey
	if errors.As(err, &nsk) {
		return nil, notFound
	}
	if err != nil {
		return nil, err
	}
	return out.Body, nil
}
